version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
      - "5173:5173"
    env_file:
      - dev.env
    volumes:
      - .:/usr/src/app
      - ./apps/client:/usr/src/app/apps/client
      - ./apps/server:/usr/src/app/apps/server
    command: npm run start:dev
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    env_file:
      - dev.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dbadmin:
    image: dpage/pgadmin4
    env_file:
      - dev.env
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
