version: "3.8"

services:
  app:
    image: bafonins/t0d0-app:main
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env.production
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
