FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json turbo.json ./
COPY apps/client/package.json ./apps/client/package.json
COPY apps/server/package.json ./apps/server/package.json

RUN npm install
