version: "3.8"

services:
  app:
    image: bafonins/t0d0-app:main
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - prod.env
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    env_file:
      - prod.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
