CREATE TABLE IF NOT EXISTS users (
    id uuid PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4(),
    username VARCHAR(255) NOT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS todos (
    id uuid PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4(),
    title VARCHAR(255) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT false,
    frozen BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "parentId" uuid,
    "ownerId" uuid NOT NULL
);

ALTER TABLE todos
ADD CONSTRAINT fk_todos_parentId
FOREIGN KEY ("parentId") REFERENCES todos(id) ON DELETE CASCADE;

ALTER TABLE todos
ADD CONSTRAINT fk_todos_ownerId
FOREIGN KEY ("ownerId") REFERENCES users(id) ON DELETE CASCADE;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
