name: Lint

on: pull_request

jobs:
  run-tests:
    name: Lint apps
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install CI dependencies
        run: npm ci

      - name: Run eslint
        run: npm run lint
